---

node_config_directory: "/etc/ovn-scale-test"
container_config_directory: "/var/lib/ovn-scale-test/config_files"

# For all-in-one deployment, use "root"
deploy_user: "root"

###################
# Docker options
###################

ovn_db_image: "huikang/ovn-scale-test-ovn"
ovn_chassis_image: "huikang/ovn-scale-test-ovn"

rally_image: "huikang/ovn-scale-test-rally"


###################
# Emulation options
###################

ovn_database_alias_ip: "172.16.20.100/16"
ovn_database_device: "eth0.3239"

ovn_chassis_start_cidr: "172.16.200.10/16"
ovn_chassis_device: "eth0.3239"

# Total number of emulated chassis
ovn_number_chassis: 5


########################
# Rally workload options
########################
network_start_cidr: "172.16.201.0/24"
network_number: "5"
ports_per_network: "5"

# from 0 to network_number, 0 means even distribution (default)
networks_per_sandbox: "0"

acls_per_port: "1"

########################
# OVS Repository to test
########################
ovs_repo: "https://github.com/openvswitch/ovs.git"
ovs_branch: "master"
