---

node_config_directory: "/etc/ovn-scale-test"
container_config_directory: "/var/lib/ovn-scale-test/config_files"

deploy_user: "root"

###################
# Docker options
###################

ovn_db_image: "ovn-scale-test-ovn"
ovn_chassis_image: "ovn-scale-test-ovn"

rally_image: "ovn-scale-test-rally"

# Valid options are [ missing, always ]
image_pull_policy: "missing"

###################
# Emulation options
###################

ovn_database_alias_ip: "172.16.20.100"
ovn_database_device: "eth0"

ovn_chassis_start_cidr: "172.16.200.10/16"
ovn_chassis_device: "eth0"

# Total number of emulated chassis
ovn_number_chassis: 5


########################
# Rally workload options
########################
network_start_cidr: "172.16.201.0/24"
network_number: "5"
ports_per_network: "50"
acls_per_port: "5"

################
# OVS Repository
################
ovs_repo: "https://github.com/openvswitch/ovs.git"
ovs_branch: "master"
