---

node_config_directory: "/etc/ovn-scale-test"
ontainer_config_directory: "/var/lib/ovn-scale-test/config_files"

deploy_user: "rally"

###################
# Docker options
###################

ovn_db_image: "huikang/ovn-scale-test-ovn"
ovn_chassis_image: "huikang/ovn-scale-test-ovn"

rally_image: "huikang/ovn-scale-test-rally"


###################
# Emulation options
###################

ovn_database_alias_ip: "172.16.20.100/16"
ovn_database_device: "eth1"

ovn_chassis_start_cidr: "172.16.200.10/16"
ovn_chassis_device: "eth1"

# Total number of emulated chassis
ovn_number_chassis: 5

# pin container to cores, e.g., "29,30,31"
north_db_cpu_set: ""
south_db_cpu_set: ""
northd_cpu_set: ""

########################
# Rally workload options
########################
network_start_cidr: "172.16.201.0/24"
network_number: "5"
ports_per_network: "1"

########################
# OVS Repository to test
########################
ovs_repo: "https://github.com/openvswitch/ovs.git"
ovs_branch: "master"
