---
- name: delete OVN control plane containers
  docker:
    name: "{{ item }}"
    image: "{{ ovn_db_image_full }}"
    pull: always
    state: absent
  with_items:
    - "ovn-north-database"
    - "ovn-south-database"
    - "ovn-northd"
  when:
    - inventory_hostname in groups['ovn-control']

- name: delete shared volume for ovn control plane
  command: docker volume rm ovn-run
  when:
    - inventory_hostname in groups['ovn-control']

- name: delete OVN chassis
  docker:
    name: "sandbox-{{ item.1 }}"
    image: "{{ ovn_db_image_full }}"
    pull: always
    privileged: yes
    net: host
    detach: True
    state: absent
  delegate_to: "{{ groups['emulation-hosts'][ item.0 ] }}"
  with_together:
        - "{{ dmi_data['ip_index'] }}"
        - "{{ dmi_data['ip_index_list'] }}"
  when:
    - inventory_hostname in groups['emulation-hosts']
  ignore_errors: yes

- name: delete ip alias on the ovn control host
  command: "ip a del {{ ovn_database_alias_ip }} dev {{ ovn_database_device }}"
  when:
    - inventory_hostname in groups['ovn-control']
  ignore_errors: yes

- name: delete ip alias on the emulation host
  command: "ip a del {{ item.1 }}/{{ dmi_data['prefixlen'] }} dev {{ ovn_chassis_device }}"
  delegate_to: "{{ groups['emulation-hosts'][ item.0 ] }}"
  with_together:
    - "{{ dmi_data['ip_index'] }}"
    - "{{ dmi_data['ip_index_list'] }}"
  when:
    - inventory_hostname in groups['emulation-hosts']
  ignore_errors: yes

- name: delete deploy user
  user:
    name: "{{ deploy_user }}"
    state: absent
    remove: yes
    move_home: yes
