---
- name: delete OVN database
  docker:
    name: ovn-database
    image: "{{ ovn_db_image_full }}"
    pull: always
    state: absent
  when:
    - inventory_hostname in groups['ovn-database']

- name: Generate IP lists pair for emulated chassis
  generate_chassis_ip_pairs:
    start_cidr: "{{ ovn_chassis_start_cidr }}"
    group_size: "{{ groups['emulation-hosts'] | length }}"
    num_ip: "{{ ovn_number_chassis }}"
  register: dmi_data
  when:
    - inventory_hostname in groups['emulation-hosts']

- name: delete OVN chassis
  docker:
    name: "sandbox-{{ item.1 }}"
    image: "{{ ovn_db_image_full }}"
    pull: always
    privileged: yes
    net: host
    detach: True
    state: absent
  delegate_to: "{{ groups['emulation-hosts'][ item.0 ] }}"
  with_together:
        - "{{ dmi_data['ip_index'] }}"
        - "{{ dmi_data['ip_index_list'] }}"
  when:
    - inventory_hostname in groups['emulation-hosts']
  ignore_errors: yes

- name: delete ip alias on the ovn database host
  command: "ip a del {{ ovn_database_alias_ip }}/32 dev {{ ovn_database_device }}"
  when:
    - inventory_hostname in groups['ovn-database']
  ignore_errors: yes

- name: delete ip alias on the emulation host
  command: "ip a del {{ item.1 }}/16 dev {{ ovn_chassis_device }}"
  delegate_to: "{{ groups['emulation-hosts'][ item.0 ] }}"
  with_together:
    - "{{ dmi_data['ip_index'] }}"
    - "{{ dmi_data['ip_index_list'] }}"
  when:
    - inventory_hostname in groups['emulation-hosts']
  ignore_errors: yes

- name: delete rally user
  user:
    name: rally
    state: absent
    remove: yes
    move_home: yes

# TODO:
#- name: delete ip alias
#  command:
